language: bash
sudo: required
services:
  - docker

before_install:
  - docker version
  - ls

jobs:
  include:

    # ---- Debian 9  -----------------------------------------------------------

    - stage: Debian-9
      script:

        - echo "==> Show version ..."
        - docker run -it --rm chusiang/vim-and-vi-mode:debian9 vim --version

        - echo "==> Install ..."
        - docker run -it -v $PWD:/srv chusiang/vim-and-vi-mode:debian9 /bin/sh -c "cd /srv && make install" . | tee output.debian-9.log

        - echo "==> Check ..."
        - grep "==> Done." output.debian-9.log
